config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'home/index'

  root to: "home#index"
  Rails.application.routes.draw do
  get 'static_pages/about'

  get 'static_pages/contact'

    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      password: 'users/password'
    }
  end

  resources :users
  
  resources :businesses
  

end

app/models/business.rb
class Business < ActiveRecord::Base
	belongs_to :user
	has_many :locations, dependent: :destroy

	# for paperclip attachment 
  	has_attached_file :image
	validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
	validates_presence_of :name, :category

	accepts_nested_attributes_for :locations, reject_if: :all_blank, allow_destroy: true

	validate :check_location

	# Business must have at least one location
	def check_location
		if locations.empty? or locations.all? {|location| location.marked_for_destruction? }
	      errors.add(:base, 'Business must have at least one location')
	    end
	end
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :business
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum role: [:user, :admin]

  # for paperclip attachment 
  has_attached_file :profile_image
  validates_attachment :profile_image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

  has_many :businesses

  # for pundit
  after_initialize :set_default_role, :if => :new_record?
  def set_default_role
    self.role ||= :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_business, only: [:show, :edit, :update, :destroy]

	def index
		@businesses = current_user.businesses if current_user.businesses.present?
	end

	def new
		@user = current_user
		@business = Business.new 
	end

	def create
		@business = Business.new(business_params.merge(user_id: current_user.id))
		if @business.save
			flash[:notice] = "New business information is created successfully."
			redirect_to business_path(@business)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @business.update(business_params)
			flash[:notice] = "Business information is updated successfully."
			redirect_to business_path(@business)
		else
			render 'edit'				
		end	
	end
	
	def show
	end	

	def destroy
		@business.destroy
		redirect_to businesses_path
	end

	private

	def set_business
		@business = Business.find(params[:id])
	end	

	def business_params
		params.require(:business).permit(:name, :category, :image, :is_active, :user_id, locations_attributes: [:id, :location, :type_of_services, :description, :cost, :is_active, :business_id, :_destroy])
	end	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_sign_up_params, only: [:create]
  before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :first_name, :last_name, :street_address, :city, :sub_division_of_country, :country, :postal_code, :profile_image) }
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :first_name, :last_name, :street_address, :city, :sub_division_of_country, :country, :postal_code, :profile_image) }
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/businesses/_form.html.erb
<%= form_for @business, html: { multipart: true } do |f| %>

  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% @business.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div><br>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_area :category %>
  </div><br>
  <div class="field">
    <%= f.label :is_active %><br>
    <%= f.check_box :is_active %>
  </div><br>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div><br>

  <h3>Add Locations Details</h3>
    <div id="locations">
      <%= f.fields_for :locations do |location| %>
        <%= render 'location_fields', f: location %>
      <% end %>
      <div class="links">
        <%= link_to_add_association 'Add Location', f, :locations %>
      </div>
    </div>
  <br>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/businesses/_location_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :location %><br/>
    <%= f.text_field :location %>
  </div><br/>
  <div class="field">
    <%= f.label :type_of_services %><br/>
    <%= f.text_field :type_of_services %>
  </div><br/>
  <div class="field">
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </div><br/>
  <div class="field">
    <%= f.label :cost %><br/>
    <%= f.number_field :cost %>
  </div><br/>
  <div class="field">
    <%= f.label :is_active %><br/>
    <%= f.check_box :is_active %>
  </div><br/>
  <%= link_to_remove_association "Remove Location", f %>
</div>

app/views/businesses/edit.html.erb
<h1>Editing Business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<% if @businesses.present? %>

<h1>Business Information</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Active</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <td><%= business.name %></td>
        <td><%= business.category %></td>
        <td><%= business.is_active ? "Yes" : "No" %></td>
        <td><%= image_tag(business.image.url,:width => 150, :height => 150, :crop => :fill) if business.image? %>
        </td>
        <td><%= link_to 'Show', business %></td>
        <td>
          <%= link_to 'Edit', edit_business_path(business) %>
        </td>
        <td><%= link_to 'Destroy', business, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% else %>
  <h3>No business information is added.</h3>
<% end %>
<br/><br/>

<%= link_to 'New Business', new_business_path %>

app/views/businesses/new.html.erb
<h1>New Business</h1>
<%= render 'form' %><br/>
<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @business.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @business.category %>
</p>

<p>
	<strong>Active:</strong>	
	<%= @business.is_active ? "Yes" : "No" %>
</p>

<p>
	<strong>Image:</strong>
	<%= image_tag(@business.image.url,:width => 150, :height => 150, :crop => :fill) if @business.image? %>
</p>

<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
<p>Find me in app/views/home/index.html.erb</p>

<h3><%= link_to "Business Details", businesses_path %></h3>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>">Emregistry</a>
    </div>
    <div>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to 'Sign Up', new_user_registration_path %>
          </li>
          <li>
            <%= link_to 'Sign In', new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Emregistry</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/header' %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>